[package]
name = "Mahjong-score-calc-tool"
version = "0.1.0"
authors = ["たた <pf35301@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
